site_name: pytest-testit-parametrize
site_description: A pytest plugin for uploading parameterized tests parameters into TMS TestIT
site_author: Ilya Romanchenko

theme: readthedocs

repo_url: https://github.com/iromanchenko-cyrm/pytest-testit-parametrize

pages:
- Home: index.md
